---
- name: View AWS machines
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - aws_cluster.yml
  tasks:
    - ec2_instance_facts:
        region: "{{region}}"
        filters:
          "instance-state-name": running
          "tag:Name": "{{clustername}}"
      register: instance_list
    - debug: var=instance_list

    - set_fact:
        instance_ids="{{instance_list.instances|map(attribute='instance_id')|list}}"
    - debug: 
        msg: "{{instance_ids}}"

    - ec2:
        region: us-west-2
        instance_ids: "{{instance_ids}}"
        state: absent
      when: instance_ids|length > 0 
